package com.example.yusm.mypractise.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.yusm.mypractise.greendao.Student;
import com.example.yusm.mypractise.greendao.User;
import com.example.yusm.mypractise.History;

import com.example.yusm.mypractise.greendao.StudentDao;
import com.example.yusm.mypractise.greendao.UserDao;
import com.example.yusm.mypractise.greendao.HistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final StudentDao studentDao;
    private final UserDao userDao;
    private final HistoryDao historyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(User.class, userDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        historyDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
